version: "3"

services:
  osmosisd:
    image: osmolabs/osmosis:7.1.0
    user: "${UID}:${GID}"
    volumes:
      - ./config:/osmosis/.osmosisd/config
      - ./data:/osmosis/.osmosisd/data
    command:
      - start
    networks:
      - osmosis
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
      - "9091:9091"
networks:
  osmosis:
    driver: bridge
