version: "3"

services:
  osmosisd:
    image: osmolabs/osmosis:7.1.0
    volumes:
      - ./config:/osmosis/.osmosisd/config
    networks:
      - osmosis
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
      - "9091:9091"
    command:
      - start

networks:
  osmosis:
    driver: bridge
