version: "3"

services:
  terrad:
    image: terramoney/localterra-core:0.4.6
    volumes:
      - ./config:/root/.terrad/config
    networks:
      - terra
    ports:
      - "26657:26657"
    command: terrad start
  lcd:
    image: terramoney/localterra-core:0.4.6
    depends_on:
      - terrad
    volumes:
      - ./config:/root/.terrad/config
    networks:
      - terra
    ports:
      - "1317:1317"
    command: terracli rest-server --laddr=tcp://0.0.0.0:1317 --node=tcp://terrad:26657 --trust-node=true --unsafe-cors
  oracle:
    image: terramoney/pseudo-feeder:0.4.7
    depends_on:
      - terrad
      - lcd
    networks:
      - terra
    environment:
      TESTNET_LCD_URL: http://lcd:1317
    command: start
  postgres:
    image: postgres:11
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - terra
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
  fcd-collector:
    image: terramoney/fcd:0.5.0
    depends_on:
      - terrad
      - lcd
      - postgres
    volumes:
      - ./logs:/app/logs
    networks:
      - terra
    env_file: fcd.env
    command: collector
  fcd-api:
    image: terramoney/fcd:0.5.0
    depends_on:
      - terrad
      - lcd
      - postgres
    volumes:
      - ./logs:/app/logs
    networks:
      - terra
    ports:
      - 3060:3060
    env_file: fcd.env
    command: start
  # redis:
  #   image: redis:latest
  #   networks:
  #     - terra
  #   ports:
  #     - "6379:6379"

networks:
  terra:
    driver: bridge
