version: "3"

services:
  osmosisd:
    image: osmolabs/osmosis:7.1.0
    user: "${UID}:${GID}"
    volumes:
      - ./config:/osmosis/.osmosisd/config
      - ./data:/osmosis/.osmosisd/data
    command:
      - start
    network_mode: host