# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

##### main base config options #####

# The maximum gas amount can be spent for contract query.
# The contract query will invoke contract execution vm,
# so we need to restrict the max usage to prevent DoS attack
contract-query-gas-limit = "3000000"

# The flag to specify whether print contract logs or not
contract-debug-mode = "false"

# The WASM VM memory cache size in MiB not bytes
contract-memory-cache-size = "500"
